### ISSUE TITLE
Roles?

### ISSUE THREAD

**Issue by TokugawaTFC** [Gwyrdain/apprentices-workshop#93] opened 2016-05-01 15:10 UTC
We should have at least two roles for the workshop. One would be an Area coordinator role and the other author.

The AC role would be able to see all areas that are on the workshop. The author role would have the current permission set.

**Comment by tyn-** [comment] 2016-05-01 15:27
People should be able to play around with an area privately, and could
share any submission candidate with the AC.  Is there a compelling reason
for all all areas to be visible to the AC by default?

**Comment by TokugawaTFC** [comment] 2016-05-01 15:31
In case it's abandoned if appropriate we can have someone else continue the work on it.

**Comment by Gwyrdain** [comment] 2016-05-01 15:36
In those cases the author would have requested and obtained permission to write the area from AC's (i.e., not just someone poking around with an idea).  From a process perspective, maybe you just ask that AC's be given "share" rights on their area after stage one approval?

**Comment by Gwyrdain** [comment] 2016-05-01 15:41
Interestingly at present you can delete a shared area, but not execute an ownership transfer.  Additional thought is probably required, but at present the process for re-assigning could be: download .are, delete old area, give .are to new author who would then import or work it manually.

**Comment by TokugawaTFC** [comment] 2016-05-01 16:45
That seems like a lot of work just to get an area to someone else. ;)

If they got upset they could delete the file and be done with it. Then all that work would be gone. I guess that raises the question if authors should be able to delete are files at all as well.

**Comment by tyn-** [comment] 2016-05-01 17:23
We need to clarify from a policy standpoint when an area is assigned/gifted
to TFC - i.e. when the area is under the control of TFC and its agents.  To
my way of thinking, this is when the area is submitted to the ACs for
installation (and any final clean up), but I'm not sure if that's clarified
in the AWG.  If not, it should be.  I know that we originally made it very
clear that once an area was submitted to TFC and we accepted it, the area
"belongs" to the game, and we could use/edit/or not use that area as we see
fit.

Until an area is assigned to TFC, we should not unilaterally hand an area
to someone else to complete.  Doing so would not be ethical, as it's the
author's work, not our's.

It's different if the original author doesn't wish to continue *and* gives
us permission to have someone else complete the zone.

I'd be in favor of a checkbox that explicitly and irrevocably releases an
area to TFC, with the appropriate disclaimer that upon submission, the area
is assigned to and owned by TFC.  This would change area ownership to the
TFC AC group.  We would make that part of the acceptance process prior to
an area being installed.

**Comment by Cordir** [comment] 2016-05-01 17:35
I feel firmly that until such time as a zone is *installed* it belongs to the Author.  I worked on Aerie Volant because Pitt *gave* authorization & authorship to Kerriariadne when he got tired of working on it, and Kerri *gave* authorization to me, in writing, to take up the project.  If he hadn't, I wouldn't have worked on it.  Yes, it's a bummer when projects don't get finished, and the AC's have put time into them as well -- but it's the author's work until it's "published" on the mud.  

Yes: An author should retain the ability to remove/delete their work from the Apprentice's Workshop at any point prior to install. 

No: the Area Coordinators shouldn't get to see every zone being worked on here. The Apprentice's Workshop is certainly *customized* for TFC, but it isn't *owned* by TFC -- people may well use it to build zones for other muds.

**Comment by Cordir** [comment] 2016-05-01 17:41
RE: Ownership transfers of shared areas --- I had a shared area I was working on with DarkClaw. I Transferred Ownership to her, and that removed it from being shared with me. I can no longer see the zone at all.  I'm not sure if that's working as intended or not.

**Comment by tyn-** [comment] 2016-05-01 18:23
"I feel firmly that until such time as a zone is *installed* it belongs to
the Author."

While I respect Cordir's opinion, it is appropriate that we secure said
area transfer prior to that area being loaded into TFC test.  At this
point, the area is (or should be) complete and has been submitted as an
installation candidate.  In order to qualify as an installation candidate,
area assignment to TFC should be a prerequisite.

Should we later decide that the area will not be installed (though I can't
envision why this would happen at such a late stage), we would release the
area back to the author(s).

This helps to ensure that every area we have on a TFC server (live or test)
belongs to the game, and definitively answers the question of whether we
have permission to use it.

**Comment by Cordir** [comment] 2016-05-02 12:59
I have zones loaded onto Test prior to the zone being turned over to the Area Coordinators - sometimes as many as four times - to do various checks that are much easier in a live environment where one can walk around and visualize the zone.  So I don't think that it's presence on Test should be the transfer of ownership. 

Once the Area Coordinators have the zone, they can make whatever changes they like. Some of those changes might be fundamental enough, that it completely alters the vision of the author.  I can imagine a time in which an author, faced with these changes, might no longer want their work to be installed, despite all the effort they and others have put into the zone.

**Comment by TokugawaTFC** [comment] 2016-05-03 00:12
The only things altered are things in the area writers guidelines. We really **don't** like having to tell an author to change things we know they might not like to change. On the other hand if you are writing an area for the mud you go into it knowing there are guidelines and you will have to conform to them. It's like writing something for pay, if the editor does not like something or asks for changes you make the required changes or the writing piece is not published.

**Comment by Gwyrdain** [comment] 2016-05-04 06:08
I have added warning messages to both the "share" and "transfer ownership" actions to better describe the current de facto consequences of these.

Further TFC staff level discussions/decisions can, and no doubt will, take place in a more appropriate environment; so, I am closing this issue and will await specific feature requests (i.e., new "issues") that are aligned with new or amended (and hopefully published) policies.

**Closed by Gwyrdain** 2016-05-04 06:08 UTC
Labels: question
